name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t abhitsahu/nx-backend:latest -f backend/Dockerfile backend/
          docker push abhitsahu/nx-backend:latest

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker stop nx-backend || true
            docker rm nx-backend || true
            docker pull abhitsahu/nx-backend:latest
            docker run -d -p 4000:4000 \
              --name nx-backend \
              --env-file /home/azureuser/nx_football/.env \
              abhitsahu/nx-backend:latest
